### PR TITLE
Show a reasonable message for reindexing an empty database

### PR DESCRIPTION
**Pull request by aquajach**
When the database is empty, sunspot raises error Error **using progress bar: Max must be a positive integer** from progress bar gem. There's no mistake here, but users can hardly understand what is going on by the message. 

A few questions in stackoverflow (e.g. http://stackoverflow.com/questions/25244964/rails-sunspot-reindex-progress-bar-max-must-be-a-positive-integer#autocomment53976291) have been asked, so I think it's not only me that found the message is confusing.

### CODE REVIEW

**Comment by bragboy** [comment]
@aquajach - I recently added two more rails files `rails-4.1.0` and `rails-4.2.0`. Can you rebase and add the `progress-bar` gemfile to these and resubmit?

**Comment by aquajach** [comment]
Thanks @bragboy . I just did that, please check.

**Comment by bragboy** [comment]
Thanks @aquajach for the PR

**Comment by aquajach** [comment]
👍@bragboy

**Pull request merged**
