### PR TITLE
Allow using methods with keyword arguments in search DSL

### PR DESCRIPTION
**Pull request by s4na**
This is the code that was temporarily reverted in this PR.( https://github.com/sunspot/sunspot/pull/1029 )
I have made adjustments to ensure the CI passes.

refs: https://github.com/sunspot/sunspot/pull/1026

### CODE REVIEW

**Comment by andreslemik** [comment]
please, merge this PR

**Comment by s4na** [comment]
@serggl
Could I possibly get a review?

**Comment by serggl** [comment]
@s4na I believe this should be updated with the latest Master to make all required status checks run

**Comment by s4na** [comment]
@serggl 
Thank you for the review.
I've updated with the latest Master.
All required status checks should run now.

**Comment by s4na** [comment]
Thank you.

**Pull request merged**
