### PR TITLE
Ruby 3 and 3.1

### PR DESCRIPTION
**Pull request by s4na**
Hello,

I've taken over this PR (https://github.com/sunspot/sunspot/pull/1027) to adapt Sunspot for use with Ruby 3 and Ruby 3.1.

Permission has been obtained from @njakobsen 

refs: https://github.com/sunspot/sunspot/pull/1027#issuecomment-1598960872

### CODE REVIEW

**Comment by s4na** [comment]
It seems that the test didn't fail, but rather the GitHub Actions Job failed to launch. Could you please retry the GitHub Actions?

Screenshot 2023-06-22 at 10 09 38

**Comment by s4na** [comment]
@serggl 
Could I possibly get a review?

**Review by serggl — APPROVED** [review]
👍🏽

**Comment by njakobsen** [comment]
@s4na Thanks for bringing this one home.

**Pull request merged**
