### PR TITLE
Solr joins

### PR DESCRIPTION
**Pull request by mikeauclair**
I took a quick stab at adding rudimentary support for Solr joins to sunspot; looking for some feedback regarding approach on this.

### CODE REVIEW

**Comment by alexandru-calinoiu** [comment]
Hi, can someone point me to documentation related to joins and some usage examples?

**Comment by heaven** [comment]
Hi, you can check here: https://github.com/sunspot/sunspot#joins Nested joins wouldn't work as the required patch wasn't merged into Solr yet (AFAIK). At the very bottom of the joins sections there're a few examples of generated Solr queries.

**Comment by alexandru-calinoiu** [comment]
thank you,

As far as I can't tell is not possible to de order_by on joined fields, do you know of something else?

**Comment by heaven** [comment]
Unfortunately no.

**Pull request merged**
