### PR TITLE
Option to set query parser to dismax via sunspot.yml

### PR DESCRIPTION
**Pull request by northband**
This pull request adds the option to set the query parser to dismax vs. the default edismax.  In order to do so a new param can be added to the sunspot.yml called `query_parser`. If the setting is not found then sunspot defaults to edismax.  

Ex:

```
production:
  solr:
    hostname: search.your-server.com
    port: 8984
    path: /solr-master
    log_level: WARNING
  auto_commit_after_request: false
  query_parser: dismax
```

This may make it easier for those who are using an up-to-date app that requires interfacing an older version of Solr w/o having to monkey patch.

### CODE REVIEW

**Comment by sent1nel** [comment]
How well did this work out for you? I'm building a search engine for a client and I've found eDisMax to be a little too strict for our users...

**Comment by northband** [comment]
It's been a while, but if I recall correctly this worked out well for us as we were trying to run the old gem on an updated version of Solr.  However, shortly after we decided to phase out our Solr setup in favor of going a different direction.

**Comment by sent1nel** [comment]
Ah, thank you! I opened another issue, #929, with my own problem. I've forked and I'm cleaning up my fork to use Lucene instead of eDisMax, similar to what you did here, until I can figure out why eDisMax queries don't work as I expect them to.

**Comment by serggl** [comment]
@northband I would give this go if you don't mind fixing merge conflicts and adding some basic description for this in README

**Comment by sent1nel** [comment]
An update on my end: the behavior I was seeing was caused by our analyzer pipeline, which I've since sorted out.

**Comment by mlh758** [comment]
Closing due to age and some conflicts.

**Pull request closed without merging**
