### PR TITLE
Spellcheck

### PR DESCRIPTION
**Pull request by scpike**
@njakobsen I saw your comment on #43, but I don't think that branch is complete. It's got code for parsing a solr response with spellcheck=true set, but it doesn't handle setting the parameter while constructing the search through the DSL (@nz  let me know if I'm wrong there please). I've been using that code, combined with the DSL and tests from https://github.com/jobseekerltd/sunspot/commit/7c92c536d6eb500b10dcc7d6fa33870429bdbc82, and some corrections of my own, for about a year in production. I finally got around to upgrading my app to rails 4, and want to come back to using the mainline sunspot. 

I also wrote some documentation for the README. 

I'm more than happy to do more work to get this merged, so let me know what you'd like to see.

### CODE REVIEW

**Comment by joneslee85** [comment]
@scpike I know it's been a long time, but since there is people who are interested in this work, can you please get it rebase?

**Comment by scpike** [comment]
@joneslee85 I can spend a little time on this over the next day or two. Are you a sunspot project maintainer who could merge it, and does the code look good?

**Comment by njakobsen** [comment]
I can take a look at it once it's ready. It's important to include in the readme both the problem the new feature is solving, and how to use it.

**Comment by joneslee85** [comment]
I could help merge once the code is thoroughly reviewed

**Comment by scpike** [comment]
@njakobsen, glad you're available. I've merged master into this branch rather than trying to rebase all the commits. I haven't looked at the actual code, which I wrote a long time ago and don't remember, but I did write what seemed like a reasonable README, and tests are passing except on 1.8.7 (which doesn't seem to pass on master itself):  https://github.com/scpike/sunspot/blob/f4d027c24e189bb50fa88e3851415681827eab84/README.md#spellcheck

Let me know what you think.

**Comment by njakobsen** [comment]
I'm ready to take the plunge on it unless anyone else has any comments. The last thing would be to fix line 33 in the spellcheck_spec so the ruby 1.8.7 test doesn't fail. I think the method call just needs to be moved up to the previous line.

**Comment by scpike** [comment]
@njakobsen I fixed my code, but it still doesn't pass on 1.8.7 due to the version of rsolr not supporting 1.8.7.

**Comment by njakobsen** [comment]
Yup. Looks like I should just remove 1.8.7 support.

**Pull request merged**
