### PR TITLE
Ruby3

### PR DESCRIPTION
**Pull request by njakobsen**
Fixing Ruby 3.0 compatibility

### CODE REVIEW

**Comment by serggl** [comment]
is TravisCI setup broken? No test run results are available for me in this PR

**Comment by njakobsen** [comment]
I noticed that too. I haven't been actively developing Sunspot for several years so I assigned the last collaborator to commit anything.

**Comment by serggl** [comment]
Blocked by https://github.com/sunspot/sunspot/pull/1029 currently

**Comment by serggl** [comment]
@njakobsen Can you please update your PR with latest `master` branch changes? And also add ruby 3 to the build matrix in the new ci workflow file

**Comment by njakobsen** [comment]
Done.

**Comment by serggl** [comment]
@njakobsen I think the Appraisal file needs to be edited as well https://github.com/sunspot/sunspot/blob/master/sunspot_rails/Appraisals#L54

I believe only Rails 7 supports ruby 3+. It also will be cool to add Rails 7 into the Appraisal file

**Comment by serggl** [comment]
@njakobsen Seems like this line should add additional restriction for ruby versions (lass than 3), right?

image

**Comment by s4na** [comment]
@njakobsen 
Hello,

I would like to use sunspot with Ruby 3. I've noticed this branch hasn't been active recently. Could I take over and update it for Ruby 3 compatibility? I'm interested in contributing, and I'm open to any suggestions.

Thanks.

**Comment by njakobsen** [comment]
@s4na That would be great. I haven't had a chance to resolve the remaining issue in the test suite.

**Comment by serggl** [comment]
Closed in favor of #1034

**Pull request closed without merging**
