### PR TITLE
[#1045] fix modular models fq type_field

### PR DESCRIPTION
**Pull request by hsw15192617273**
About #1045

### CODE REVIEW

**Review by serggl — COMMENTED** [review]
@hsw15192617273 I think we only need to escape the `value` when it contains colons

**Comment by hsw15192617273** [comment]
> @hsw15192617273 I think we only need to escape the `value` when it contains colons

ok, i will change my code.  
and when i fix spec code, i found modular models type is worked in solr 8.x, maybe i need some time to figure out the reason for this issue

**Comment by hsw15192617273** [comment]
I take solr debug mode to search `type:Info\:\:Firm`, and solr8.x / solr 9.x have different `parsed_filter_queries` value
Xnip2024-06-18_14-24-35

I believe this is because different Solr versions have different configurations in SolrSchema, and Sunspot has not adapted to the higher versions of Solr, causing this issue. like #1037

- - -

return this issue, add double quotes can resolves this.
Xnip2024-06-18_14-27-38

but i found spec has this code
```ruby
  it 'builds search for multiple types' do
    session.search(Post, Namespaced::Comment)
    expect(connection).to have_last_search_with(:fq => ['type:(Post OR Namespaced\:\:Comment)'])
  end
```
It might also be necessary to make some modifications to `Restriction::AnyOf`

**Review by serggl — APPROVED** [review]
Nice work 🙌🏽

**Pull request merged**
